### ISSUE TITLE
Nombre de las funciones no coincide

### ISSUE THREAD

**Issue by kholostyak17** [YifanYes/Jest-Unit-Testing#1]
-Al ejecutar el test, da fallo en que la función `FromDollar**To**Yen` no se encuentra, al parecer esto es debido a que hay un pequeño error en el nombre, pues la funcion esta definida como `FromDollar**to**Yen`. Sucede lo mismo con la tercera función, pero una vez solventado esto, el ejercicio compila y pasa todos los test :heavy_check_mark: 

https://github.com/YifanYes/Jest-Unit-Testing/blob/0a963988362461ca12755f99f8c86d7079f007b9/app.js#L18
https://github.com/YifanYes/Jest-Unit-Testing/blob/0a963988362461ca12755f99f8c86d7079f007b9/app.js#L23
https://github.com/YifanYes/Jest-Unit-Testing/blob/0a963988362461ca12755f99f8c86d7079f007b9/app.js#L28

**Comment by YifanYes** [comment]
Ay es verdad, ya lo he solucionado, maldito case sensitive
